{{- if ne .Values.image.registry "Quay" }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'image-puller-rb'
  namespace: {{ .Values.image.namespace.name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "quarkus-template.serviceAccountName" . }}
    namespace: {{ .Values.namespace.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'
{{- end}}  




